# Generated by Django 4.2.7 on 2026-03-20 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_answer', models.TextField()),
                ('score', models.FloatField(default=0.0)),
                ('feedback', models.TextField(blank=True)),
                ('matched_keywords', models.JSONField(default=list)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'interview_logs',
            },
        ),
        migrations.CreateModel(
            name='InterviewSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('difficulty', models.CharField(default='medium', max_length=10)),
                ('total_questions', models.IntegerField(default=0)),
                ('completed_questions', models.IntegerField(default=0)),
                ('total_score', models.FloatField(default=0.0)),
                ('average_score', models.FloatField(default=0.0)),
                ('is_completed', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'interview_sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('python', 'Python'), ('java', 'Java'), ('javascript', 'JavaScript'), ('django', 'Django'), ('react', 'React'), ('sql', 'SQL'), ('system_design', 'System Design'), ('hr', 'HR / Behavioural'), ('dsa', 'Data Structures & Algorithms'), ('general', 'General')], max_length=50)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('question', models.TextField()),
                ('expected_keywords', models.JSONField(default=list)),
                ('sample_answer', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'question_bank',
            },
        ),
    ]
